v3.0.4
wb-apps/tmz-schemas pull request #22
Opened 2024-02-15 21:53 UTC by digitalartcrew

* __Add Schemas:__
  * `tmz:news:command:inspect-article-seo`
* Use `triniti/schemas` v3.0.4

2024-02-15 21:55 UTC, digitalartcrew commented
Don't merge until deployed: [Triniti Schema](https://github.com/triniti/schemas/pull/106)

2024-02-23 20:03 UTC, efjacobson commented
@digitalartcrew need to compile them after adding the xml. also dont forget the event

2024-02-28 19:39 UTC, efjacobson requested changes
@digitalartcrew bump the version in .nvmrc to at least v20.10.0

looking good overall though, just a few other minor things below

2024-02-28 19:39 UTC, efjacobson commented on composer.json
>      "php": ">=8.1",
@digitalartcrew bump to >=8.3

2024-02-28 19:39 UTC, efjacobson commented on composer.json
@digitalartcrew lets change the semver for everything except pbjc to be `^N` eg

`"gdbots/schemas": "3.0.3"` -> `"gdbots/schemas": "^3",`

2024-02-28 19:39 UTC, efjacobson commented on package.json
@digitalartcrew same `^N` changes here please

2024-02-29 20:39 UTC, efjacobson commented on composer.json
@digitalartcrew do it for all of them

2024-02-29 20:39 UTC, efjacobson commented on package.json
@digitalartcrew do it for all of them

2024-03-05 00:36 UTC, efjacobson approved these changes

2024-03-05 00:37 UTC, merged